Repository spooooony/Spoony-iOS, pull requests merged in 2025-06, with the labels that each got.

#338 [Feat/#335] 자동 로그인 구현
  Spoony-iOS/Spoony-iOS/Network/Auth/KeychainManager.swift
  Spoony-iOS/Spoony-iOS/Network/Auth/TokenAuthenticator.swift
  Spoony-iOS/Spoony-iOS/Network/Auth/TokenCredential.swift
  Spoony-iOS/Spoony-iOS/Network/Base/Providers.swift
  Spoony-iOS/Spoony-iOS/Network/Model/AuthModel/RefreshResponse.swift
  Spoony-iOS/Spoony-iOS/Network/Service/AuthService/AuthService.swift
  Spoony-iOS/Spoony-iOS/Network/Service/AuthService/RefreshService.swift
  Spoony-iOS/Spoony-iOS/Network/TargetType/AuthTargetType.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Coordinator/AppCoordinator/AppCoordinatorView.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Auth/AuthenticationManager.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Login/LoginFeature.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Setting/AccountManagement/AccountManagementFeature.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Setting/AccountManagement/withdraw/WithdrawFeature.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Onboarding/OnboardingFeature.swift
Labels: feat, Juri

#340 Feat/#336 프로필수정
  Spoony-iOS/Spoony-iOS/Resource/Assets.xcassets/Icon/ic_imageFail.imageset/Contents.json
  Spoony-iOS/Spoony-iOS/Resource/Assets.xcassets/Icon/ic_imageFail.imageset/Frame 2085665361.svg
  Spoony-iOS/Spoony-iOS/Resource/Components/BottomSheet/ProfileImageBottomSheet.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Coordinator/TabRootCoordinator/TabRootCoordinator.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Edit/EditProfileFeature.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Edit/EditProfileImageView.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Edit/EditProfileView.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Edit/ProfileImageType.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Register/State/RegisterFeature.swift
Labels: feat, Anyoung

#349 [Feat/#333] 삭제하기 API 구현 및 필요 없는 파일제거
  Spoony-iOS/Spoony-iOS/Network/Base/Providers.swift
  Spoony-iOS/Spoony-iOS/Network/DependencyKey/DetailUseCaseKey.swift
  Spoony-iOS/Spoony-iOS/Network/TargetType/PostTargetType.swift
  Spoony-iOS/Spoony-iOS/Resource/Components/Navigation/NavigationBarStyle.swift
  Spoony-iOS/Spoony-iOS/Resource/Components/PlaceHolderCardView/PlaceCard.swift
  Spoony-iOS/Spoony-iOS/Resource/Extension/DependencyValues+.swift
  Spoony-iOS/Spoony-iOS/Resource/Helper/PopupModifier.swift
  Spoony-iOS/Spoony-iOS/Resource/Tab/Model/ViewType.swift
  Spoony-iOS/Spoony-iOS/Resource/Tab/NavigationManager.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Coordinator/ExploreCoordinator/ExploreCoordinator.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Coordinator/MapCoordinator/MapCoordinator.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Coordinator/TabCoordinator/TabCoordinator.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Coordinator/TabRootCoordinator/TabRootCoordinator.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Coordinator/TabRootCoordinator/TabRootCoordinatorView.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Detail/Domain/RepositoryInterface/DetailRepositoryInterface.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Detail/Domain/UseCase/DetailUseCase.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Detail/Presentation/DetailView.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Detail/Presentation/DetailViewStore.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Explore/ExploreFeature.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Explore/Search/ExploreSearchFeature.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Explore/Search/ExploreSearchView.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Explore/View/Explore.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Home/MapFeature.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Post/Data/DataMapping/PostResponseDTO.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Post/Data/DataMapping/UserInfoResponseDTO.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Post/Data/Repository/PostRepository.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Post/Domain/Entity/PostModel.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Post/Domain/RepositoryInterface/PostRepositoryInterface.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Post/Domain/UseCase/PostUseCase.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Post/Presentation/MockPostUseCase.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Post/Presentation/PostFeature.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Post/Presentation/PostView.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Register/State/RegisterFeature.swift
Labels: feat, fix, Th1ngjin

#364 [Fix/#363] 데이트픽커 QA 반영
  Spoony-iOS/Spoony-iOS/Resource/Components/BottomSheet/DatePicker/DatePickerBottomSheet.swift
  Spoony-iOS/Spoony-iOS/Resource/Components/BottomSheet/DatePicker/DatePickerManager.swift
  Spoony-iOS/Spoony-iOS/Resource/Components/BottomSheet/DatePicker/UIPickerCoordinator.swift
Labels: fix, Anyoung

#365 [Bug/#359] QA 반영
  Spoony-iOS/Spoony-iOS/Network/Model/BlockUserModel.swift
  Spoony-iOS/Spoony-iOS/Network/Model/ExploreModel/FilteredFeedResponse.swift
  Spoony-iOS/Spoony-iOS/Network/Model/ExploreModel/ReviewSearchListResponse.swift
  Spoony-iOS/Spoony-iOS/Network/Model/FeedResponse.swift
  Spoony-iOS/Spoony-iOS/Network/Model/MyPageModel/UserInfoResponse.swift
  Spoony-iOS/Spoony-iOS/Network/Model/MyPageModel/UserProfileResponse.swift
  Spoony-iOS/Spoony-iOS/Resource/Components/BottomSheet/LocationPickerBottomSheet.swift
  Spoony-iOS/Spoony-iOS/Resource/Components/SpoonyTextEditor.swift
  Spoony-iOS/Spoony-iOS/Resource/Extension/Date+.swift
  Spoony-iOS/Spoony-iOS/Resource/Helper/AlertModifier.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Explore/ExploreFeature.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Explore/Filtering/FilteringBottomSheet.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Explore/Model/FeedEntity.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Explore/Search/ExploreSearchFeature.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Explore/Search/ExploreSearchView.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Explore/View/Explore.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Explore/View/ExploreCell.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/OtherProfile/OtherProfileFeature.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Profile/ProfileFeature.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Setting/BlockedUsersFeature/BlockedUsersView.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Onboarding/OnboardingFeature.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Post/Data/DataMapping/UserInfoResponseDTO.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Post/Presentation/PostFeature.swift
Labels: fix, Juri

#375 [Fix/#353] - 리뷰 상세 QA 진행 하였습니다.
  Spoony-iOS/Spoony-iOS/Resource/Helper/ToastModifier.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Post/Data/DataMapping/PostResponseDTO.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Post/Domain/Entity/PostModel.swift
Labels: fix, Th1ngjin

#383 [Fix/#361] 자잘한 QA 개선
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Edit/EditProfileFeature.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Following/FollowFeature.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Following/FollowResponseModel.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Post/Presentation/PostFeature.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Post/Presentation/PostView.swift
Labels: fix, Th1ngjin

#389 [Fix: #387] - 글 짤림 현상 수정
  Spoony-iOS/Spoony-iOS/Resource/Components/BottomSheet/ProfileImageBottomSheet.swift
Labels: fix, Anyoung

#392 [Feat/#391] 스푼 박살내기 구현 90% 완료
  Spoony-iOS/Spoony-iOS/Resource/Components/Navigation/CustomNavigationBar.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Coordinator/TabRootCoordinator/TabRootCoordinator.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Post/Presentation/PostFeature.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Post/Presentation/PostView.swift
Labels: feat, Th1ngjin

#374 [Refactor/#373] @macro를 사용한 반복코드 제거
  Spoony-iOS/Spoony-iOS.xcodeproj/project.pbxproj
  Spoony-iOS/Spoony-iOS/Network/NetworkingMacros/.gitignore
  Spoony-iOS/Spoony-iOS/Network/NetworkingMacros/Package.swift
  Spoony-iOS/Spoony-iOS/Network/NetworkingMacros/Sources/NetworkingMacros/NetworkingMacros.swift
  Spoony-iOS/Spoony-iOS/Network/NetworkingMacros/Sources/NetworkingMacrosClient/main.swift
  Spoony-iOS/Spoony-iOS/Network/NetworkingMacros/Sources/NetworkingMacrosMacros/NetworkingMacrosMacro.swift
  Spoony-iOS/Spoony-iOS/Network/Service/HomeService/HomeService.swift
Labels: feat, fix, refactor, Jihoon

#395 [Fix/#394] 스푼뽑기 수정
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Attendance/AttendanceFeature.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Post/Presentation/PostFeature.swift
Labels: fix, Jihoon

#403 [Fix/#401] - 굿모닝 QA
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Following/FollowFeature.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Following/FollowListView.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Post/Presentation/PostView.swift
Labels: fix, Th1ngjin

#406 [fix: #405]post 요청중 뒤로가기 버튼 클릭 가능 현상 수정
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Register/State/RegisterFeature.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Register/View/Register.swift
Labels: fix, Anyoung

#407 Fix/#404 2차수정qa이지훈
  Spoony-iOS/Spoony-iOS/Network/Service/MyPageService/MyPageService.swift
  Spoony-iOS/Spoony-iOS/Network/TargetType/MyPageTargetType.swift
  Spoony-iOS/Spoony-iOS/Resource/Components/PlaceHolderCardView/PlaceCard.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Coordinator/MapCoordinator/MapCoordinator.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Home/Home.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Home/NMapView.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Attendance/AttendanceInfoSheetView.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Attendance/AttendanceView.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/OtherProfile/OtherProfileFeature.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/OtherProfile/OtherProfileView.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/SearchLocation/SearchLocationFeature.swift
Labels: feat, Jihoon

#412 [fix: #408] 22일QA반영
  Spoony-iOS/Spoony-iOS/Network/Model/RegisterModel/RegisterPostRequest.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Register/State/RegisterFeature.swift
  Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Register/View/Register.swift
Labels: fix, Anyoung
